# Generated by Django 5.2.13 on 2026-04-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CACHORRO', 'CACHORRO'), ('GATO', 'GATO')])),
                ('nome', models.CharField()),
                ('genero', models.CharField()),
                ('idade', models.IntegerField()),
                ('castrado', models.BooleanField()),
            ],
        ),
    ]
