# Generated by Django 6.0.5 on 2026-05-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(verbose_name='castrado'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='genero',
            field=models.CharField(max_length=20, verbose_name='gênero'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(verbose_name='idade em anos'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('CACHORRO', 'CACHORRO'), ('GATO', 'GATO')], max_length=20, verbose_name='tipo de animal'),
        ),
    ]
