# Generated by Django 6.0.5 on 2026-05-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_castrado_alter_animal_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Adotante',
                'verbose_name_plural': 'Adotantes',
            },
        ),
    ]
