# Generated by Django 5.2.15 on 2026-06-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_animalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fotos_att',
            field=models.FileField(blank=True, null=True, upload_to='animals/', verbose_name='fotos+att'),
        ),
    ]
